[build]
  command = "npm run build"
  publish = ".next"

# Environment variables
[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# For Next.js routing
[[plugins]]
  package = "@netlify/plugin-nextjs"